services:
  app:
    image: phone-frontend
    build:
      context: ./phone-frontend
    ports:
      - 3000:80
    volumes:
      - ./phone-frontend:/usr/src/app
    environment:
      - REACT_APP_BACKEND=http://localhost:3001
    container_name: phone-frontend
    depends_on:
      - server
  server:
    image: phone-backend
    build:
      context: ./phone-backend
    environment:
      - NODE_ENV=development
    ports:
     - 3001:3001
    volumes:
      - ./phone-backend:/usr/src/app
    container_name: phone-backend
  nginx:
    image: nginx
    build: ./phone-frontend
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
